// Unicode Symbol Collection — data mapped to Lucide icon categories
// Each entry: { c: character, n: name }
// Formats (codepoint, HTML entity, CSS escape, JS escape) are derived at runtime.
// "note" cites the corresponding Lucide category and count for reference.

const CATEGORIES = [
    {
        name: "Accessibility",
        note: "Lucide: Accessibility (31)",
        symbols: [
            { c: "♿", n: "Wheelchair Symbol" },
            { c: "🦯", n: "White Cane" },
            { c: "🦽", n: "Manual Wheelchair" },
            { c: "🦾", n: "Motorized Wheelchair" },
            { c: "🧍", n: "Person Standing" },
            { c: "🧏", n: "Deaf Person" },
            { c: "🚹", n: "Mens Symbol" },
            { c: "🚺", n: "Womens Symbol" },
            { c: "🚻", n: "Restroom Symbol" },
            { c: "🚼", n: "Baby Symbol" }
        ]
    },
    {
        name: "Accounts & Access",
        note: "Lucide: Accounts & access (146)",
        symbols: [
            { c: "🔑", n: "Key" },
            { c: "🔒", n: "Locked" },
            { c: "🔓", n: "Unlocked" },
            { c: "🔏", n: "Locked With Key" },
            { c: "🗝", n: "Old Key" },
            { c: "🚪", n: "Door" },
            { c: "🔐", n: "Locked With Pen" },
            { c: "🔎", n: "Magnifying Glass" },
            { c: "🕶", n: "Sunglasses" },
            { c: "🕵", n: "Detective" }
        ]
    },
    {
        name: "Animals",
        note: "Lucide: Animals (24)",
        symbols: [
            { c: "🐶", n: "Dog Face" },
            { c: "🐱", n: "Cat Face" },
            { c: "🐭", n: "Mouse Face" },
            { c: "🐹", n: "Hamster Face" },
            { c: "🐰", n: "Rabbit Face" },
            { c: "🦊", n: "Fox" },
            { c: "🐻", n: "Bear" },
            { c: "🐼", n: "Panda" },
            { c: "🐨", n: "Koala" },
            { c: "🐯", n: "Tiger" },
            { c: "🦁", n: "Lion" },
            { c: "🐮", n: "Cow" },
            { c: "🐷", n: "Pig" },
            { c: "🐸", n: "Frog" },
            { c: "🐵", n: "Monkey" },
            { c: "🐔", n: "Chicken" },
            { c: "🐧", n: "Penguin" },
            { c: "🐦", n: "Bird" },
            { c: "🦆", n: "Duck" },
            { c: "🦉", n: "Owl" },
            { c: "🐝", n: "Honeybee" },
            { c: "🦋", n: "Butterfly" },
            { c: "🐢", n: "Turtle" },
            { c: "🐙", n: "Octopus" },
            { c: "🐬", n: "Dolphin" },
            { c: "🦄", n: "Unicorn" }
        ]
    },
    {
        name: "Arrows",
        note: "Lucide: Arrows (214) — U+2190–21FF, U+2794–27BF",
        symbols: [
            { c: "←", n: "Left Arrow" },
            { c: "→", n: "Right Arrow" },
            { c: "↑", n: "Up Arrow" },
            { c: "↓", n: "Down Arrow" },
            { c: "↔", n: "Left Right Arrow" },
            { c: "↕", n: "Up Down Arrow" },
            { c: "↖", n: "Up Left Arrow" },
            { c: "↗", n: "Up Right Arrow" },
            { c: "↘", n: "Down Right Arrow" },
            { c: "↙", n: "Down Left Arrow" },
            { c: "↩", n: "Left Arrow With Hook" },
            { c: "↪", n: "Right Arrow With Hook" },
            { c: "↰", n: "Up Arrow With Tip Left" },
            { c: "↱", n: "Up Arrow With Tip Right" },
            { c: "↲", n: "Down Arrow With Tip Left" },
            { c: "↳", n: "Down Arrow With Tip Right" },
            { c: "↶", n: "Anticlockwise Top Semicircle" },
            { c: "↷", n: "Clockwise Top Semicircle" },
            { c: "↺", n: "Anticlockwise Open Circle" },
            { c: "↻", n: "Clockwise Open Circle" },
            { c: "↼", n: "Left Harpoon With Barb Up" },
            { c: "↽", n: "Left Harpoon With Barb Down" },
            { c: "⇀", n: "Right Harpoon With Barb Up" },
            { c: "⇁", n: "Right Harpoon With Barb Down" },
            { c: "⇄", n: "Right Arrow Over Left" },
            { c: "⇅", n: "Up Arrow Left Of Down" },
            { c: "⇆", n: "Left Arrow Over Right" },
            { c: "↨", n: "Up Down Arrow With Base" },
            { c: "↵", n: "Down Arrow With Corner Left" },
            { c: "↸", n: "North West Arrow To Long Bar" },
            { c: "↽↼", n: "Double Harpoon" },
            { c: "⇋", n: "Left Right Arrow Over Harpoon" },
            { c: "⇌", n: "Right Left Arrow Over Harpoon" },
            { c: "⇐", n: "Double Left Arrow" },
            { c: "⇒", n: "Double Right Arrow" },
            { c: "⇑", n: "Double Up Arrow" },
            { c: "⇓", n: "Double Down Arrow" },
            { c: "⇔", n: "Double Left Right Arrow" },
            { c: "⇕", n: "Double Up Down Arrow" },
            { c: "⇖", n: "Double Up Left Arrow" },
            { c: "⇗", n: "Double Up Right Arrow" },
            { c: "⇘", n: "Double Down Right Arrow" },
            { c: "⇙", n: "Double Down Left Arrow" },
            { c: "⇚", n: "Triple Left Arrow" },
            { c: "⇛", n: "Triple Right Arrow" },
            { c: "⇝", n: "Right Arrow With Loop" },
            { c: "⇦", n: "Leftwards White Arrow" },
            { c: "⇧", n: "Upwards White Arrow" },
            { c: "⇨", n: "Rightwards White Arrow" },
            { c: "⇩", n: "Downwards White Arrow" },
            { c: "⇪", n: "Upwards White Arrow On Pedestal" },
            { c: "⇵", n: "Downwards Arrow Left Of Upwards" },
            { c: "➔", n: "Heavy Right Arrow" },
            { c: "➜", n: "Heavy Round Right Arrow" },
            { c: "➡", n: "Black Right Arrow" },
            { c: "⬅", n: "Left Black Arrow" },
            { c: "⬆", n: "Up Black Arrow" },
            { c: "⬇", n: "Down Black Arrow" },
            { c: "⤴", n: "Arrow Pointing Up Right" },
            { c: "⤵", n: "Arrow Pointing Down Right" },
            { c: "➵", n: "Black Curved Right Arrow" },
            { c: "➹", n: "Heavy Concave Right Arrow" },
            { c: "➼", n: "Right Arrow With Triangle Head" },
            { c: "➿", n: "Wavy Right Arrow" }
        ]
    },
    {
        name: "Buildings",
        note: "Lucide: Buildings (24)",
        symbols: [
            { c: "⌂", n: "House" },
            { c: "🏠", n: "House Building" },
            { c: "🏡", n: "House With Garden" },
            { c: "🏢", n: "Office Building" },
            { c: "🏣", n: "Japanese Post Office" },
            { c: "🏥", n: "Hospital" },
            { c: "🏦", n: "Bank" },
            { c: "🏨", n: "Hotel" },
            { c: "🏪", n: "Convenience Store" },
            { c: "🏫", n: "School" },
            { c: "🏬", n: "Department Store" },
            { c: "🏭", n: "Factory" },
            { c: "🏯", n: "Japanese Castle" },
            { c: "🏰", n: "Castle" },
            { c: "⛪", n: "Church" },
            { c: "🏘", n: "Stadium" },
            { c: "🏛", n: "Classical Building" },
            { c: "🏙", n: "Cityscape" },
            { c: "🏟", n: "Stadium" },
            { c: "🏞", n: "National Park" }
        ]
    },
    {
        name: "Charts",
        note: "Lucide: Charts (31) — block elements U+2580–259F",
        symbols: [
            { c: "▀", n: "Upper Half Block" },
            { c: "▁", n: "Lower One Eighth Block" },
            { c: "▂", n: "Lower Quarter Block" },
            { c: "▃", n: "Lower Three Eighths Block" },
            { c: "▄", n: "Lower Half Block" },
            { c: "▅", n: "Lower Five Eighths Block" },
            { c: "▆", n: "Lower Three Quarters Block" },
            { c: "▇", n: "Lower Seven Eighths Block" },
            { c: "█", n: "Full Block" },
            { c: "▉", n: "Left Seven Eighths Block" },
            { c: "▊", n: "Left Three Quarters Block" },
            { c: "▋", n: "Left Five Eighths Block" },
            { c: "▌", n: "Left Half Block" },
            { c: "▍", n: "Left Three Eighths Block" },
            { c: "▎", n: "Left Quarter Block" },
            { c: "▏", n: "Left One Eighth Block" },
            { c: "▖", n: "Quadrant Lower Left" },
            { c: "▗", n: "Quadrant Lower Right" },
            { c: "▘", n: "Quadrant Upper Left" },
            { c: "▙", n: "Quadrant Upper Left Lower Right" },
            { c: "▚", n: "Quadrant Upper Left Lower Right Diagonal" },
            { c: "▛", n: "Quadrant Upper Left Upper Right Lower Left" },
            { c: "▜", n: "Quadrant Upper Left Upper Right Lower Right" },
            { c: "▝", n: "Quadrant Upper Right" },
            { c: "▞", n: "Quadrant Upper Right Lower Left" },
            { c: "▟", n: "Quadrant Upper Right Lower Left Lower Right" },
            { c: "◢", n: "Black Lower Right Triangle" },
            { c: "◣", n: "Black Lower Left Triangle" },
            { c: "◤", n: "Black Upper Left Triangle" },
            { c: "◥", n: "Black Upper Right Triangle" },
            { c: "▰", n: "Black Parallelogram" },
            { c: "▱", n: "White Parallelogram" }
        ]
    },
    {
        name: "Communication",
        note: "Lucide: Communication (56)",
        symbols: [
            { c: "✉", n: "Envelope" },
            { c: "☎", n: "Telephone" },
            { c: "✆", n: "Telephone Location" },
            { c: "📞", n: "Telephone Receiver" },
            { c: "📟", n: "Pager" },
            { c: "📠", n: "Fax" },
            { c: "📧", n: "Email" },
            { c: "💌", n: "Love Letter" },
            { c: "📨", n: "Incoming Envelope" },
            { c: "📩", n: "Envelope With Arrow" },
            { c: "📤", n: "Outbox Tray" },
            { c: "📥", n: "Inbox Tray" },
            { c: "📦", n: "Package" },
            { c: "📫", n: "Postbox" },
            { c: "📪", n: "Closed Mailbox Lowered" },
            { c: "📬", n: "Open Mailbox Raised" },
            { c: "📭", n: "Open Mailbox Lowered" },
            { c: "💬", n: "Speech Balloon" },
            { c: "💭", n: "Thought Balloon" },
            { c: "🗣", n: "Speaking Head" },
            { c: "📢", n: "Loudspeaker" },
            { c: "📣", n: "Megaphone" },
            { c: "📱", n: "Mobile Phone" },
            { c: "📲", n: "Mobile Phone With Arrow" }
        ]
    },
    {
        name: "Connectivity",
        note: "Lucide: Connectivity (94)",
        symbols: [
            { c: "🔗", n: "Link" },
            { c: "📶", n: "Antenna Bars" },
            { c: "⚡", n: "Lightning" },
            { c: "🔌", n: "Electric Plug" },
            { c: "🔋", n: "Battery" },
            { c: "💡", n: "Light Bulb" },
            { c: "🌐", n: "Globe With Meridians" },
            { c: "🌍", n: "Globe Europe" },
            { c: "🌎", n: "Globe Americas" },
            { c: "🌏", n: "Globe Asia" },
            { c: "⚛", n: "Atom Symbol" },
            { c: "📡", n: "Satellite Antenna" },
            { c: "⌨", n: "Keyboard" },
            { c: "🖥", n: "Desktop Computer" },
            { c: "🖨", n: "Printer" }
        ]
    },
    {
        name: "Cursors",
        note: "Lucide: Cursors (34) — pointing hands U+261A–261F",
        symbols: [
            { c: "↖", n: "Up Left Arrow" },
            { c: "↗", n: "Up Right Arrow" },
            { c: "↘", n: "Down Right Arrow" },
            { c: "↙", n: "Down Left Arrow" },
            { c: "☜", n: "White Left Pointing Index" },
            { c: "☝", n: "White Up Pointing Index" },
            { c: "☞", n: "White Right Pointing Index" },
            { c: "☟", n: "White Down Pointing Index" },
            { c: "☚", n: "Black Left Pointing Index" },
            { c: "☛", n: "Black Right Pointing Index" },
            { c: "👆", n: "Up Pointing Hand" },
            { c: "👇", n: "Down Pointing Hand" },
            { c: "👈", n: "Left Pointing Hand" },
            { c: "👉", n: "Right Pointing Hand" },
            { c: "☝️", n: "Pointing Up (emoji)" },
            { c: "🖱", n: "Three Button Mouse" },
            { c: "👋", n: "Waving Hand" }
        ]
    },
    {
        name: "Design",
        note: "Lucide: Design (147)",
        symbols: [
            { c: "✎", n: "Lower Right Pencil" },
            { c: "✏", n: "Pencil" },
            { c: "✐", n: "Upper Right Pencil" },
            { c: "✍", n: "Writing Hand" },
            { c: "✒", n: "Black Nib" },
            { c: "✑", n: "White Nib" },
            { c: "🎨", n: "Artist Palette" },
            { c: "🖍", n: "Red Crayon" },
            { c: "🖌", n: "Lower Left Paintbrush" },
            { c: "🖼", n: "Framed Picture" },
            { c: "◆", n: "Black Diamond" },
            { c: "◇", n: "White Diamond" },
            { c: "▲", n: "Black Up Triangle" },
            { c: "△", n: "White Up Triangle" },
            { c: "▼", n: "Black Down Triangle" },
            { c: "▽", n: "White Down Triangle" },
            { c: "○", n: "White Circle" },
            { c: "●", n: "Black Circle" },
            { c: "◐", n: "Circle With Left Half Black" },
            { c: "◑", n: "Circle With Right Half Black" },
            { c: "◒", n: "Circle With Lower Half Black" },
            { c: "◓", n: "Circle With Upper Half Black" },
            { c: "◔", n: "Circle With Upper Right Quadrant" },
            { c: "◕", n: "Circle With All But Upper Left" },
            { c: "◖", n: "Left Half Black Circle" },
            { c: "◗", n: "Right Half Black Circle" }
        ]
    },
    {
        name: "Coding & Development",
        note: "Lucide: Coding & development (251)",
        symbols: [
            { c: "{", n: "Left Brace" },
            { c: "}", n: "Right Brace" },
            { c: "(", n: "Left Parenthesis" },
            { c: ")", n: "Right Parenthesis" },
            { c: "[", n: "Left Bracket" },
            { c: "]", n: "Right Bracket" },
            { c: "<", n: "Less Than" },
            { c: ">", n: "Greater Than" },
            { c: "/", n: "Slash" },
            { c: "\\", n: "Backslash" },
            { c: "|", n: "Vertical Bar" },
            { c: "&", n: "Ampersand" },
            { c: "^", n: "Caret" },
            { c: "~", n: "Tilde" },
            { c: "%", n: "Percent" },
            { c: "#", n: "Number Sign" },
            { c: "@", n: "At Sign" },
            { c: "!", n: "Exclamation" },
            { c: "?", n: "Question Mark" },
            { c: ":", n: "Colon" },
            { c: ";", n: "Semicolon" },
            { c: "`", n: "Backtick" },
            { c: "=", n: "Equals" },
            { c: "+", n: "Plus" },
            { c: "-", n: "Minus" },
            { c: "*", n: "Asterisk" },
            { c: "⌘", n: "Command Key" },
            { c: "⌥", n: "Option Key" },
            { c: "⌃", n: "Control Key" },
            { c: "⇧", n: "Shift Key" },
            { c: "⌦", n: "Delete Right" },
            { c: "⌫", n: "Delete Left" },
            { c: "⎋", n: "Escape" },
            { c: "↵", n: "Return" },
            { c: "⎆", n: "Enter Symbol" },
            { c: "⎇", n: "Alternative Key" },
            { c: "⎈", n: "Helicopter Symbol" },
            { c: "↹", n: "Tab" },
            { c: "␣", n: "Open Box Space" },
            { c: "␡", n: "Delete Symbol" },
            { c: "␀", n: "Null Symbol" },
            { c: "💻", n: "Laptop" },
            { c: "🖥", n: "Desktop Computer" },
            { c: "⌨", n: "Keyboard" },
            { c: "🖮", n: "Computer Mouse" },
            { c: "💾", n: "Floppy Disk" },
            { c: "💿", n: "Optical Disc" },
            { c: "🧮", n: "Abacus" }
        ]
    },
    {
        name: "Devices",
        note: "Lucide: Devices (179)",
        symbols: [
            { c: "📱", n: "Mobile Phone" },
            { c: "💻", n: "Laptop" },
            { c: "⌨", n: "Keyboard" },
            { c: "🖥", n: "Desktop Computer" },
            { c: "🖱", n: "Three Button Mouse" },
            { c: "🖲", n: "Trackball" },
            { c: "💽", n: "Minidisc" },
            { c: "💾", n: "Floppy Disk" },
            { c: "💿", n: "Optical Disc" },
            { c: "📀", n: "DVD" },
            { c: "📺", n: "Television" },
            { c: "📻", n: "Radio" },
            { c: "⏰", n: "Alarm Clock" },
            { c: "⌚", n: "Watch" },
            { c: "📟", n: "Pager" },
            { c: "🎙", n: "Studio Microphone" },
            { c: "🎚", n: "Level Slider" },
            { c: "🎛", n: "Control Knobs" },
            { c: "⏱", n: "Stopwatch" },
            { c: "⏲", n: "Timer" },
            { c: "⏳", n: "Hourglass" },
            { c: "📶", n: "Antenna Bars" },
            { c: "🔋", n: "Battery" },
            { c: "🔌", n: "Electric Plug" }
        ]
    },
    {
        name: "Emoji",
        note: "Lucide: Emoji (45) — smileys U+1F600+, emoticons U+2639–263B",
        symbols: [
            { c: "😀", n: "Grinning Face" },
            { c: "😃", n: "Smiling With Open Mouth" },
            { c: "😄", n: "Smiling With Open Mouth And Smiling Eyes" },
            { c: "😁", n: "Grinning With Smiling Eyes" },
            { c: "😆", n: "Squinting Face" },
            { c: "😅", n: "Sweat Smile" },
            { c: "😂", n: "Face With Tears Of Joy" },
            { c: "🙂", n: "Slightly Smiling Face" },
            { c: "😊", n: "Smiling Eyes" },
            { c: "😍", n: "Heart Eyes" },
            { c: "🤩", n: "Star Struck" },
            { c: "😘", n: "Blowing A Kiss" },
            { c: "😛", n: "Tongue Out" },
            { c: "😜", n: "Winking Tongue" },
            { c: "😝", n: "Squinting Tongue" },
            { c: "🤗", n: "Hugging Face" },
            { c: "🤔", n: "Thinking Face" },
            { c: "🤨", n: "Raised Eyebrow" },
            { c: "😐", n: "Neutral Face" },
            { c: "😑", n: "Expressionless" },
            { c: "😶", n: "Face Without Mouth" },
            { c: "😏", n: "Smirking Face" },
            { c: "🙄", n: "Rolling Eyes" },
            { c: "😬", n: "Grimacing" },
            { c: "😌", n: "Relieved" },
            { c: "😔", n: "Pensive" },
            { c: "😪", n: "Sleepy" },
            { c: "😴", n: "Sleeping" },
            { c: "😷", n: "Face With Medical Mask" },
            { c: "🤯", n: "Exploding Head" },
            { c: "🥳", n: "Party Face" },
            { c: "😎", n: "Cool Face" },
            { c: "🤓", n: "Nerd Face" },
            { c: "😕", n: "Confused" },
            { c: "😣", n: "Persevering" },
            { c: "😢", n: "Crying Face" },
            { c: "😭", n: "Loudly Crying" },
            { c: "😱", n: "Screaming" },
            { c: "😠", n: "Angry Face" },
            { c: "😡", n: "Pouting Face" },
            { c: "😈", n: "Smiling Devil" },
            { c: "☹", n: "Frowning Face" },
            { c: "☺", n: "Smiling Face" },
            { c: "☻", n: "Black Smiling Face" }
        ]
    },
    {
        name: "File Icons",
        note: "Lucide: File icons (166)",
        symbols: [
            { c: "📄", n: "Page Facing Up" },
            { c: "📁", n: "File Folder" },
            { c: "📂", n: "Open File Folder" },
            { c: "📋", n: "Clipboard" },
            { c: "📎", n: "Paperclip" },
            { c: "🖇", n: "Linked Paperclips" },
            { c: "🗂", n: "Card Index Dividers" },
            { c: "🗃", n: "Card File Box" },
            { c: "🗄", n: "File Cabinet" },
            { c: "🗑", n: "Wastebasket" },
            { c: "📝", n: "Memo" },
            { c: "📑", n: "Bookmark Tabs" },
            { c: "📰", n: "Newspaper" },
            { c: "📓", n: "Notebook" },
            { c: "📕", n: "Closed Book" },
            { c: "📖", n: "Open Book" },
            { c: "📗", n: "Green Book" },
            { c: "📘", n: "Blue Book" },
            { c: "📙", n: "Orange Book" },
            { c: "📚", n: "Books" },
            { c: "📒", n: "Ledger" },
            { c: "📃", n: "Page With Curl" },
            { c: "📅", n: "Calendar" },
            { c: "📆", n: "Tear Off Calendar" },
            { c: "📇", n: "Card Index" },
            { c: "📈", n: "Bar Chart" },
            { c: "📉", n: "Upward Trend" },
            { c: "📊", n: "Downward Trend" }
        ]
    },
    {
        name: "Finance",
        note: "Lucide: Finance (58) — currency U+20A0–20CF",
        symbols: [
            { c: "$", n: "Dollar Sign" },
            { c: "¢", n: "Cent Sign" },
            { c: "£", n: "Pound Sign" },
            { c: "¥", n: "Yen Sign" },
            { c: "€", n: "Euro Sign" },
            { c: "₹", n: "Indian Rupee" },
            { c: "₽", n: "Russian Ruble" },
            { c: "₩", n: "Korean Won" },
            { c: "₪", n: "Shekel" },
            { c: "₺", n: "Turkish Lira" },
            { c: "₱", n: "Philippine Peso" },
            { c: "₴", n: "Ukrainian Hryvnia" },
            { c: "₿", n: "Bitcoin" },
            { c: "₫", n: "Dong" },
            { c: "₭", n: "Kip" },
            { c: "₮", n: "Tugrik" },
            { c: "₲", n: "Guarani" },
            { c: "₳", n: "Austral" },
            { c: "₵", n: "Cedi" },
            { c: "₸", n: "Tenge" },
            { c: "₰", n: "German Penny" },
            { c: "₠", n: "Euro-currency" },
            { c: "₡", n: "Colon" },
            { c: "₢", n: "Cruzeiro" },
            { c: "₣", n: "French Franc" },
            { c: "₤", n: "Lira" },
            { c: "₦", n: "Naira" },
            { c: "₧", n: "Peseta" },
            { c: "₨", n: "Rupee" },
            { c: "₼", n: "Manat" },
            { c: "₷", n: "Spesmilo" },
            { c: "¤", n: "Currency Sign" }
        ]
    },
    {
        name: "Food & Beverage",
        note: "Lucide: Food & beverage (74)",
        symbols: [
            { c: "🍎", n: "Red Apple" },
            { c: "🍋", n: "Banana" },
            { c: "🍇", n: "Grapes" },
            { c: "🍓", n: "Strawberry" },
            { c: "🍒", n: "Cherries" },
            { c: "🍉", n: "Watermelon" },
            { c: "🍊", n: "Tangerine" },
            { c: "🍔", n: "Hamburger" },
            { c: "🍟", n: "French Fries" },
            { c: "🍕", n: "Pizza" },
            { c: "🌭", n: "Hot Dog" },
            { c: "🍞", n: "Bread" },
            { c: "🥚", n: "Egg" },
            { c: "🍳", n: "Cooking" },
            { c: "🍣", n: "Sushi" },
            { c: "🍜", n: "Steaming Bowl" },
            { c: "🍛", n: "Curry Rice" },
            { c: "🍚", n: "Cooked Rice" },
            { c: "🍲", n: "Pot Of Food" },
            { c: "🍦", n: "Ice Cream" },
            { c: "🍰", n: "Shortcake" },
            { c: "🎂", n: "Birthday Cake" },
            { c: "🍫", n: "Chocolate Bar" },
            { c: "🍭", n: "Lollipop" },
            { c: "🍬", n: "Candy" },
            { c: "🍴", n: "Fork And Knife" },
            { c: "☕", n: "Hot Beverage" },
            { c: "🍵", n: "Teacup" },
            { c: "🍺", n: "Beer Mug" },
            { c: "🍷", n: "Wine Glass" },
            { c: "🍸", n: "Cocktail Glass" },
            { c: "🍾", n: "Clinking Glasses" },
            { c: "🍻", n: "Clinking Beer Mugs" },
            { c: "🥣", n: "Bowl With Spoon" },
            { c: "🍽", n: "Fork And Knife With Plate" }
        ]
    },
    {
        name: "Gaming",
        note: "Lucide: Gaming (154) — card suits, chess, dice",
        symbols: [
            { c: "♠", n: "Black Spade" },
            { c: "♣", n: "Black Club" },
            { c: "♥", n: "Black Heart" },
            { c: "♦", n: "Black Diamond" },
            { c: "♤", n: "White Spade" },
            { c: "♧", n: "White Club" },
            { c: "♡", n: "White Heart" },
            { c: "♢", n: "White Diamond" },
            { c: "♚", n: "Black Chess King" },
            { c: "♛", n: "Black Chess Queen" },
            { c: "♜", n: "Black Chess Rook" },
            { c: "♝", n: "Black Chess Bishop" },
            { c: "♞", n: "Black Chess Knight" },
            { c: "♟", n: "Black Chess Pawn" },
            { c: "♔", n: "White Chess King" },
            { c: "♕", n: "White Chess Queen" },
            { c: "♖", n: "White Chess Rook" },
            { c: "♗", n: "White Chess Bishop" },
            { c: "♘", n: "White Chess Knight" },
            { c: "♙", n: "White Chess Pawn" },
            { c: "⚀", n: "Die Face One" },
            { c: "⚁", n: "Die Face Two" },
            { c: "⚂", n: "Die Face Three" },
            { c: "⚃", n: "Die Face Four" },
            { c: "⚄", n: "Die Face Five" },
            { c: "⚅", n: "Die Face Six" },
            { c: "🎮", n: "Video Game" },
            { c: "🎲", n: "Game Die" },
            { c: "🎯", n: "Bullseye" },
            { c: "🎰", n: "Slot Machine" },
            { c: "🕹", n: "Joystick" },
            { c: "🃏", n: "Playing Card Black Joker" },
            { c: "🀄", n: "Mahjong Tile" }
        ]
    },
    {
        name: "Home",
        note: "Lucide: Home (62)",
        symbols: [
            { c: "⌂", n: "House" },
            { c: "🏠", n: "House" },
            { c: "🏡", n: "House With Garden" },
            { c: "🛋", n: "Couch And Lamp" },
            { c: "🚪", n: "Door" },
            { c: "🛏", n: "Bed" },
            { c: "🚿", n: "Shower" },
            { c: "🛁", n: "Bathtub" },
            { c: "🚽", n: "Toilet" },
            { c: "🧹", n: "Broom" },
            { c: "🧺", n: "Soap" },
            { c: "🧻", n: "Sponge" },
            { c: "🧼", n: "Squeeze Bottle" },
            { c: "🧽", n: "Broom" },
            { c: "🛾", n: "Roll Of Paper" },
            { c: "🪑", n: "Chair" }
        ]
    },
    {
        name: "Layout",
        note: "Lucide: Layout (144) — box drawing U+2500–257F",
        symbols: [
            { c: "─", n: "Light Horizontal" },
            { c: "│", n: "Light Vertical" },
            { c: "┌", n: "Light Down Right" },
            { c: "┐", n: "Light Down Left" },
            { c: "└", n: "Light Up Right" },
            { c: "┘", n: "Light Up Left" },
            { c: "├", n: "Light Vertical Right" },
            { c: "┤", n: "Light Vertical Left" },
            { c: "┬", n: "Light Horizontal Down" },
            { c: "┴", n: "Light Horizontal Up" },
            { c: "┼", n: "Light Cross" },
            { c: "━", n: "Heavy Horizontal" },
            { c: "┃", n: "Heavy Vertical" },
            { c: "┏", n: "Heavy Down Right" },
            { c: "┓", n: "Heavy Down Left" },
            { c: "┗", n: "Heavy Up Right" },
            { c: "┛", n: "Heavy Up Left" },
            { c: "┣", n: "Heavy Vertical Right" },
            { c: "┫", n: "Heavy Vertical Left" },
            { c: "┳", n: "Heavy Horizontal Down" },
            { c: "┻", n: "Heavy Horizontal Up" },
            { c: "╋", n: "Heavy Cross" },
            { c: "═", n: "Double Horizontal" },
            { c: "║", n: "Double Vertical" },
            { c: "╔", n: "Double Down Right" },
            { c: "╗", n: "Double Down Left" },
            { c: "╚", n: "Double Up Right" },
            { c: "╝", n: "Double Up Left" },
            { c: "╠", n: "Double Vertical Right" },
            { c: "╣", n: "Double Vertical Left" },
            { c: "╦", n: "Double Horizontal Down" },
            { c: "╩", n: "Double Horizontal Up" },
            { c: "╬", n: "Double Cross" },
            { c: "▓", n: "Dark Shade" },
            { c: "▒", n: "Medium Shade" },
            { c: "░", n: "Light Shade" },
            { c: "■", n: "Black Square" },
            { c: "□", n: "White Square" },
            { c: "▪", n: "Black Small Square" },
            { c: "▫", n: "White Small Square" },
            { c: "◼", n: "Black Medium Square" },
            { c: "◻", n: "White Medium Square" }
        ]
    },
    {
        name: "Mail",
        note: "Lucide: Mail (26)",
        symbols: [
            { c: "✉", n: "Envelope" },
            { c: "📧", n: "Email Symbol" },
            { c: "📨", n: "Incoming Envelope" },
            { c: "📩", n: "Envelope With Arrow" },
            { c: "📤", n: "Outbox Tray" },
            { c: "📥", n: "Inbox Tray" },
            { c: "📦", n: "Package" },
            { c: "📫", n: "Postbox" },
            { c: "📪", n: "Closed Mailbox" },
            { c: "📬", n: "Open Mailbox Up" },
            { c: "📭", n: "Open Mailbox Down" },
            { c: "💌", n: "Love Letter" },
            { c: "📌", n: "Pushpin" },
            { c: "📎", n: "Paperclip" },
            { c: "📝", n: "Memo" },
            { c: "📋", n: "Clipboard" }
        ]
    },
    {
        name: "Mathematics",
        note: "Lucide: Mathematics (77) — U+2200–22FF",
        symbols: [
            { c: "+", n: "Plus" },
            { c: "−", n: "Minus" },
            { c: "±", n: "Plus Minus" },
            { c: "∓", n: "Minus Or Plus" },
            { c: "×", n: "Multiplication" },
            { c: "÷", n: "Division" },
            { c: "=", n: "Equals" },
            { c: "≠", n: "Not Equal" },
            { c: "≡", n: "Identical To" },
            { c: "≈", n: "Almost Equal" },
            { c: "≅", n: "Approximately Equal" },
            { c: "∼", n: "Tilde" },
            { c: "∝", n: "Proportional To" },
            { c: "<", n: "Less Than" },
            { c: "≤", n: "Less Than Or Equal" },
            { c: ">", n: "Greater Than" },
            { c: "≥", n: "Greater Than Or Equal" },
            { c: "≪", n: "Much Less Than" },
            { c: "≫", n: "Much Greater Than" },
            { c: "∞", n: "Infinity" },
            { c: "√", n: "Square Root" },
            { c: "∛", n: "Cube Root" },
            { c: "∜", n: "Fourth Root" },
            { c: "∑", n: "N Ary Summation" },
            { c: "∏", n: "N Ary Product" },
            { c: "∫", n: "Integral" },
            { c: "∬", n: "Double Integral" },
            { c: "∭", n: "Triple Integral" },
            { c: "∮", n: "Contour Integral" },
            { c: "∂", n: "Partial Differential" },
            { c: "∇", n: "Nabla" },
            { c: "∆", n: "Increment" },
            { c: "∀", n: "For All" },
            { c: "∃", n: "There Exists" },
            { c: "∄", n: "There Does Not Exist" },
            { c: "∅", n: "Empty Set" },
            { c: "∈", n: "Element Of" },
            { c: "∉", n: "Not An Element Of" },
            { c: "∋", n: "Contains As Member" },
            { c: "∪", n: "Union" },
            { c: "∩", n: "Intersection" },
            { c: "⊂", n: "Subset Of" },
            { c: "⊃", n: "Superset Of" },
            { c: "⊆", n: "Subset Or Equal" },
            { c: "⊇", n: "Superset Or Equal" },
            { c: "⊊", n: "Subset Not Equal" },
            { c: "⊋", n: "Superset Not Equal" },
            { c: "⊕", n: "Circled Plus" },
            { c: "⊖", n: "Circled Minus" },
            { c: "⊗", n: "Circled Times" },
            { c: "⊘", n: "Circled Division Slash" },
            { c: "⊙", n: "Circled Dot" },
            { c: "∠", n: "Angle" },
            { c: "∡", n: "Measured Angle" },
            { c: "∥", n: "Parallel To" },
            { c: "⊥", n: "Right Angle" },
            { c: "⋅", n: "Dot Operator" },
            { c: "∘", n: "Ring Operator" },
            { c: "⋆", n: "Star Operator" },
            { c: "∗", n: "Asterisk Operator" },
            { c: "°", n: "Degree" },
            { c: "′", n: "Prime" },
            { c: "″", n: "Double Prime" },
            { c: "℃", n: "Degree Celsius" },
            { c: "℉", n: "Degree Fahrenheit" },
            { c: "Å", n: "Angstrom" },
            { c: "∴", n: "Therefore" },
            { c: "∵", n: "Because" }
        ]
    },
    {
        name: "Medical",
        note: "Lucide: Medical (43)",
        symbols: [
            { c: "⚕", n: "Staff Of Aesculapius" },
            { c: "⚛", n: "Atom Symbol" },
            { c: "☠", n: "Skull And Crossbones" },
            { c: "☢", n: "Radioactive" },
            { c: "☣", n: "Biohazard" },
            { c: "☪", n: "Star And Crescent" },
            { c: "🩺", n: "Stethoscope" },
            { c: "🩹", n: "Adhesive Bandage" },
            { c: "💊", n: "Pill" },
            { c: "💉", n: "Syringe" },
            { c: "🧬", n: "DNA" },
            { c: "🩼", n: "X Ray" },
            { c: "🚚", n: "Ambulance" },
            { c: "⚕️", n: "Medical Symbol (emoji)" }
        ]
    },
    {
        name: "Multimedia",
        note: "Lucide: Multimedia (149) — U+2399–23FA media controls",
        symbols: [
            { c: "▶", n: "Black Right Triangle" },
            { c: "◀", n: "Black Left Triangle" },
            { c: "⏸", n: "Pause Symbol" },
            { c: "⏹", n: "Stop Symbol" },
            { c: "⏺", n: "Record Symbol" },
            { c: "⏭", n: "Next Track" },
            { c: "⏮", n: "Previous Track" },
            { c: "⏯", n: "Play Or Pause" },
            { c: "⏩", n: "Fast Forward" },
            { c: "⏪", n: "Fast Reverse" },
            { c: "⏫", n: "Fast Up" },
            { c: "⏬", n: "Fast Down" },
            { c: "⏏", n: "Eject" },
            { c: "⏱", n: "Stopwatch" },
            { c: "⏲", n: "Timer" },
            { c: "⏳", n: "Hourglass Flowing" },
            { c: "⌚", n: "Watch" },
            { c: "⏰", n: "Alarm Clock" },
            { c: "🎤", n: "Microphone" },
            { c: "🎧", n: "Headphone" },
            { c: "🎙", n: "Studio Microphone" },
            { c: "🎚", n: "Level Slider" },
            { c: "🎛", n: "Control Knobs" },
            { c: "🎵", n: "Musical Note" },
            { c: "🎶", n: "Multiple Musical Notes" },
            { c: "🔇", n: "Muted Speaker" },
            { c: "🔈", n: "Speaker Low Volume" },
            { c: "🔉", n: "Speaker Medium Volume" },
            { c: "🔊", n: "Speaker High Volume" },
            { c: "📷", n: "Camera" },
            { c: "📹", n: "Video Camera" },
            { c: "🎬", n: "Clapper Board" }
        ]
    },
    {
        name: "Nature",
        note: "Lucide: Nature (23) — dingbats U+2700+ floral",
        symbols: [
            { c: "✿", n: "Black Florette" },
            { c: "❀", n: "White Florette" },
            { c: "❁", n: "Eight Petalled Outlined Florette" },
            { c: "❂", n: "Circle With Vertical Fill And Overlap" },
            { c: "❃", n: "Heavy Heart Exclamation" },
            { c: "❄", n: "Snowflake" },
            { c: "❅", n: "Tight Trifoliate Snowflake" },
            { c: "❆", n: "Heavy Chevron Snowflake" },
            { c: "❇", n: "Sparkle" },
            { c: "❈", n: "Heavy Sparkle" },
            { c: "❉", n: "Balloon Spoked Asterisk" },
            { c: "❊", n: "Eight Teardrop Spoked Propeller" },
            { c: "❋", n: "Heavy Eight Teardrop Spoked Propeller" },
            { c: "☘", n: "Shamrock" },
            { c: "❦", n: "Floral Heart" },
            { c: "❧", n: "Rotated Floral Heart" },
            { c: "✻", n: "Heavy Teardrop Spoked Asterisk" },
            { c: "✼", n: "Open Centre Asterisk" },
            { c: "🌱", n: "Seedling" },
            { c: "🌲", n: "Evergreen Tree" },
            { c: "🌳", n: "Deciduous Tree" },
            { c: "🌴", n: "Palm Tree" },
            { c: "🌵", n: "Cactus" },
            { c: "🌿", n: "Herb" },
            { c: "🍀", n: "Four Leaf Clover" },
            { c: "🍁", n: "Maple Leaf" },
            { c: "🍂", n: "Fallen Leaf" },
            { c: "🍃", n: "Leaf Fluttering" },
            { c: "🌾", n: "Sheaf Of Rice" },
            { c: "🌷", n: "Tulip" },
            { c: "🌹", n: "Rose" },
            { c: "🌻", n: "Sunflower" },
            { c: "🌼", n: "Blossom" },
            { c: "🌺", n: "Hibiscus" }
        ]
    },
    {
        name: "Navigation & Places",
        note: "Lucide: Navigation & Places (88) — stars, flags, compass",
        symbols: [
            { c: "✦", n: "Black Four Pointed Star" },
            { c: "✧", n: "White Four Pointed Star" },
            { c: "✩", n: "Stress Outlined White Star" },
            { c: "✪", n: "Circled White Star" },
            { c: "✫", n: "Open Centre Black Star" },
            { c: "✬", n: "Black Centre White Star" },
            { c: "✭", n: "Outlined Black Star" },
            { c: "✮", n: "Heavy Outlined Black Star" },
            { c: "✯", n: "Pinwheel Star" },
            { c: "✰", n: "Shadowed White Star" },
            { c: "✱", n: "Heavy Asterisk" },
            { c: "✲", n: "Open Centre Asterisk" },
            { c: "✳", n: "Eight Spoked Asterisk" },
            { c: "✴", n: "Eight Pointed Black Star" },
            { c: "✵", n: "Eight Pointed Pinwheel Star" },
            { c: "✶", n: "Six Pointed Black Star" },
            { c: "✷", n: "Eight Pointed Rectilinear Black Star" },
            { c: "✸", n: "Heavy Eight Pointed Rectilinear Black Star" },
            { c: "✹", n: "Twelve Pointed Black Star" },
            { c: "🧭", n: "Compass" },
            { c: "📍", n: "Round Pushpin" },
            { c: "📌", n: "Pushpin" },
            { c: "🗺", n: "World Map" },
            { c: "⚑", n: "Black Flag" },
            { c: "⚐", n: "White Flag" },
            { c: "🏴", n: "Waving Black Flag" },
            { c: "🏁", n: "Chequered Flag" },
            { c: "🎍", n: "Pine Decoration" },
            { c: "🏕", n: "Campsite" },
            { c: "🏖", n: "Beach With Umbrella" },
            { c: "🏜", n: "Desert" },
            { c: "🏔", n: "Snow Capped Mountain" },
            { c: "⛰", n: "Mountain" },
            { c: "⛺", n: "Tent" }
        ]
    },
    {
        name: "Notification",
        note: "Lucide: Notification (42)",
        symbols: [
            { c: "🔔", n: "Bell" },
            { c: "⚠", n: "Warning Sign" },
            { c: "🚨", n: "Police Light" },
            { c: "📢", n: "Loudspeaker" },
            { c: "📣", n: "Megaphone" },
            { c: "❗", n: "Heavy Exclamation" },
            { c: "❕", n: "White Exclamation" },
            { c: "❓", n: "Black Question Mark" },
            { c: "❔", n: "White Question Mark" },
            { c: "⭐", n: "Star" },
            { c: "🌟", n: "Glowing Star" },
            { c: "💫", n: "Dizzy Symbol" },
            { c: "⚡", n: "Lightning" },
            { c: "🔥", n: "Fire" },
            { c: "💥", n: "Collision" },
            { c: "🟢", n: "Green Circle" },
            { c: "🟡", n: "Yellow Circle" },
            { c: "🟠", n: "Orange Circle" },
            { c: "🔴", n: "Red Circle" },
            { c: "✅", n: "Check Mark Button" },
            { c: "❌", n: "Cross Mark" },
            { c: "❎", n: "Cross Mark Button" }
        ]
    },
    {
        name: "People",
        note: "Lucide: People (5) — emoticons + emoji",
        symbols: [
            { c: "☺", n: "Smiling Face" },
            { c: "☻", n: "Black Smiling Face" },
            { c: "☹", n: "Frowning Face" },
            { c: "👤", n: "Bust In Silhouette" },
            { c: "👥", n: "Busts In Silhouette" },
            { c: "🧑", n: "Person" },
            { c: "👶", n: "Baby" },
            { c: "👧", n: "Girl" },
            { c: "👦", n: "Boy" },
            { c: "👩", n: "Woman" },
            { c: "👨", n: "Man" },
            { c: "🧓", n: "Older Person" },
            { c: "👵", n: "Older Woman" },
            { c: "👴", n: "Older Man" },
            { c: "🧔", n: "Bearded Person" },
            { c: "🧏", n: "Deaf Person" },
            { c: "🤦", n: "Face Palm" },
            { c: "🤷", n: "Shrug" },
            { c: "🙇", n: "Bow" },
            { c: "🙅", n: "No Gesture" },
            { c: "🙆", n: "OK Gesture" },
            { c: "🙋", n: "Happy Person Raising Hand" }
        ]
    },
    {
        name: "Photography",
        note: "Lucide: Photography (77)",
        symbols: [
            { c: "📷", n: "Camera" },
            { c: "📸", n: "Camera With Flash" },
            { c: "📹", n: "Video Camera" },
            { c: "🎥", n: "Movie Camera" },
            { c: "🎞", n: "Film Frames" },
            { c: "💻", n: "Film Projector" },
            { c: "🎬", n: "Clapper Board" },
            { c: "📼", n: "Videocassette" },
            { c: "🔍", n: "Left Pointing Magnifier" },
            { c: "🕯", n: "Candle" },
            { c: "🎡", n: "Telescope" },
            { c: "🔬", n: "Microscope" },
            { c: "💡", n: "Light Bulb" },
            { c: "🌙", n: "Crescent Moon" },
            { c: "📘", n: "Blue Book" },
            { c: "⌚", n: "Watch" },
            { c: "🕶", n: "Sunglasses" }
        ]
    },
    {
        name: "Science",
        note: "Lucide: Science (37)",
        symbols: [
            { c: "⚛", n: "Atom Symbol" },
            { c: "⚗", n: "Alembic" },
            { c: "⚒", n: "Hammer And Pick" },
            { c: "⚖", n: "Scales" },
            { c: "🔬", n: "Microscope" },
            { c: "🎡", n: "Telescope" },
            { c: "🧪", n: "Test Tube" },
            { c: "🧫", n: "Petri Dish" },
            { c: "🧬", n: "DNA" },
            { c: "🌡", n: "Thermometer" },
            { c: "☢", n: "Radioactive" },
            { c: "☣", n: "Biohazard" },
            { c: "∇", n: "Nabla" },
            { c: "∂", n: "Partial Differential" },
            { c: "∫", n: "Integral" },
            { c: "∆", n: "Increment" },
            { c: "∞", n: "Infinity" },
            { c: "⊙", n: "Circled Dot" },
            { c: "⊕", n: "Circled Plus" },
            { c: "⊗", n: "Circled Times" },
            { c: "⌘", n: "Command Key" },
            { c: "⌥", n: "Option Key" }
        ]
    },
    {
        name: "Seasons",
        note: "Lucide: Seasons (5)",
        symbols: [
            { c: "❄", n: "Snowflake" },
            { c: "☀", n: "Sun" },
            { c: "☂", n: "Umbrella" },
            { c: "☃", n: "Snowman" },
            { c: "🍃", n: "Leaf Fluttering" },
            { c: "🌷", n: "Tulip" },
            { c: "🍁", n: "Maple Leaf" },
            { c: "🌾", n: "Sheaf Of Rice" },
            { c: "🌞", n: "Sun With Face" },
            { c: "⛄", n: "Snowman Without Snow" },
            { c: "🌨", n: "Snow Cloud" },
            { c: "🌼", n: "Blossom" },
            { c: "🍉", n: "Watermelon" },
            { c: "🏖", n: "Beach With Umbrella" },
            { c: "🌰", n: "Chestnut" },
            { c: "🎃", n: "Jack O Lantern" },
            { c: "🌱", n: "Seedling" }
        ]
    },
    {
        name: "Security",
        note: "Lucide: Security (59)",
        symbols: [
            { c: "⚠", n: "Warning Sign" },
            { c: "🚫", n: "No Entry" },
            { c: "☢", n: "Radioactive" },
            { c: "☣", n: "Biohazard" },
            { c: "☠", n: "Skull And Crossbones" },
            { c: "🔒", n: "Locked" },
            { c: "🔓", n: "Unlocked" },
            { c: "🔏", n: "Locked With Key" },
            { c: "🔑", n: "Key" },
            { c: "🛡", n: "Shield" },
            { c: "🛑", n: "Octagonal Sign" },
            { c: "🚷", n: "No Pedestrians" },
            { c: "🚯", n: "No Littering" },
            { c: "🚱", n: "Non Potable Water" },
            { c: "🚭", n: "No Smoking" },
            { c: "🚳", n: "No Bicycles" },
            { c: "🔞", n: "No One Under Eighteen" },
            { c: "📵", n: "No Mobile Phones" },
            { c: "⛔", n: "No Entry Sign" },
            { c: "⌘", n: "Command Key" }
        ]
    },
    {
        name: "Shapes",
        note: "Lucide: Shapes (61) — geometric U+25A0–25FF",
        symbols: [
            { c: "■", n: "Black Square" },
            { c: "□", n: "White Square" },
            { c: "▢", n: "White Square Rounded" },
            { c: "▣", n: "White Square Containing Black Square" },
            { c: "▤", n: "Square Horizontal Fill" },
            { c: "▥", n: "Square Vertical Fill" },
            { c: "▦", n: "Square Cross Fill" },
            { c: "▧", n: "Square Upper Left To Lower Right Fill" },
            { c: "▨", n: "Square Upper Right To Lower Left Fill" },
            { c: "▩", n: "Square Diagonal Cross Fill" },
            { c: "▪", n: "Black Small Square" },
            { c: "▫", n: "White Small Square" },
            { c: "▬", n: "Black Rectangle" },
            { c: "▭", n: "White Rectangle" },
            { c: "▮", n: "Black Vertical Rectangle" },
            { c: "▯", n: "White Vertical Rectangle" },
            { c: "▲", n: "Black Up Triangle" },
            { c: "△", n: "White Up Triangle" },
            { c: "▴", n: "Black Up Small Triangle" },
            { c: "▵", n: "White Up Small Triangle" },
            { c: "▼", n: "Black Down Triangle" },
            { c: "▽", n: "White Down Triangle" },
            { c: "▾", n: "Black Down Small Triangle" },
            { c: "▿", n: "White Down Small Triangle" },
            { c: "◀", n: "Black Left Triangle" },
            { c: "◁", n: "White Left Triangle" },
            { c: "▶", n: "Black Right Triangle" },
            { c: "◇", n: "White Diamond" },
            { c: "◈", n: "White Diamond Containing Small Diamond" },
            { c: "◉", n: "Fisheye" },
            { c: "◊", n: "Lozenge" },
            { c: "○", n: "White Circle" },
            { c: "●", n: "Black Circle" },
            { c: "◎", n: "Bullseye" },
            { c: "◐", n: "Circle Left Half Black" },
            { c: "◑", n: "Circle Right Half Black" },
            { c: "◒", n: "Circle Lower Half Black" },
            { c: "◓", n: "Circle Upper Half Black" },
            { c: "◔", n: "Circle Upper Right Quadrant" },
            { c: "◕", n: "Circle All But Upper Left Black" },
            { c: "◖", n: "Left Half Black Circle" },
            { c: "◗", n: "Right Half Black Circle" },
            { c: "⬛", n: "Black Large Square" },
            { c: "⬜", n: "White Large Square" },
            { c: "⬤", n: "Black Large Circle" },
            { c: "⬥", n: "Black Medium Diamond" },
            { c: "⬦", n: "White Medium Diamond" }
        ]
    },
    {
        name: "Shopping",
        note: "Lucide: Shopping (29)",
        symbols: [
            { c: "🛒", n: "Shopping Cart" },
            { c: "🛍", n: "Shopping Bags" },
            { c: "🏷", n: "Label" },
            { c: "💰", n: "Money Bag" },
            { c: "💳", n: "Credit Card" },
            { c: "🧾", n: "Receipt" },
            { c: "💸", n: "Money With Wings" },
            { c: "💱", n: "Currency Exchange" },
            { c: "🪙", n: "Coin" },
            { c: "🛎", n: "Bellhop Bell" },
            { c: "🏪", n: "Convenience Store" },
            { c: "🏬", n: "Department Store" },
            { c: "🛓", n: "Stadium" },
            { c: "₽", n: "Russian Ruble" }
        ]
    },
    {
        name: "Social",
        note: "Lucide: Social (138) — hearts + emoji",
        symbols: [
            { c: "♡", n: "White Heart" },
            { c: "♥", n: "Black Heart" },
            { c: "❤", n: "Heavy Black Heart" },
            { c: "💛", n: "Yellow Heart" },
            { c: "💚", n: "Green Heart" },
            { c: "💙", n: "Blue Heart" },
            { c: "💜", n: "Purple Heart" },
            { c: "🖤", n: "Black Heart" },
            { c: "🤍", n: "White Heart" },
            { c: "🤎", n: "Brown Heart" },
            { c: "💔", n: "Broken Heart" },
            { c: "❣", n: "Heart Exclamation" },
            { c: "💕", n: "Two Hearts" },
            { c: "💖", n: "Sparkling Heart" },
            { c: "💓", n: "Beating Heart" },
            { c: "💗", n: "Growing Heart" },
            { c: "💘", n: "Heart With Arrow" },
            { c: "💝", n: "Heart With Ribbon" },
            { c: "💞", n: "Revolving Hearts" },
            { c: "💟", n: "Heart Decoration" },
            { c: "☕", n: "Hot Beverage" },
            { c: "👍", n: "Thumbs Up" },
            { c: "👎", n: "Thumbs Down" },
            { c: "👏", n: "Clapping Hands" },
            { c: "🙌", n: "Raising Hands" },
            { c: "🤝", n: "Handshake" },
            { c: "🧡", n: "Orange Heart" }
        ]
    },
    {
        name: "Sports",
        note: "Lucide: Sports (16)",
        symbols: [
            { c: "⚽", n: "Soccer Ball" },
            { c: "⚾", n: "Baseball" },
            { c: "🏀", n: "Basketball" },
            { c: "🏈", n: "American Football" },
            { c: "🎾", n: "Tennis" },
            { c: "🏐", n: "Volleyball" },
            { c: "🏉", n: "Rugby Football" },
            { c: "🏏", n: "Cricket" },
            { c: "🏒", n: "Ice Hockey" },
            { c: "🏓", n: "Ping Pong" },
            { c: "🏸", n: "Badminton" },
            { c: "🥊", n: "Martial Arts Uniform" },
            { c: "🎱", n: "Pool" },
            { c: "🎯", n: "Bullseye" },
            { c: "⛳", n: "Flag In Hole" },
            { c: "🏅", n: "Sports Medal" },
            { c: "🥇", n: "First Place Medal" },
            { c: "🥈", n: "Second Place Medal" },
            { c: "🥉", n: "Third Place Medal" },
            { c: "🏆", n: "Trophy" },
            { c: "🎖", n: "Military Medal" },
            { c: "🎽", n: "Running Shirt" },
            { c: "🏇", n: "Horse Racing" },
            { c: "⛷", n: "Skier" },
            { c: "🏂", n: "Snowboarder" }
        ]
    },
    {
        name: "Sustainability",
        note: "Lucide: Sustainability (25)",
        symbols: [
            { c: "♻", n: "Recycling Symbol" },
            { c: "☀", n: "Sun" },
            { c: "🌱", n: "Seedling" },
            { c: "🌍", n: "Globe Europe" },
            { c: "🌎", n: "Globe Americas" },
            { c: "🌏", n: "Globe Asia" },
            { c: "💧", n: "Droplet" },
            { c: "🌳", n: "Deciduous Tree" },
            { c: "🌲", n: "Evergreen Tree" },
            { c: "🌴", n: "Palm Tree" },
            { c: "🌿", n: "Herb" },
            { c: "🍃", n: "Leaf Fluttering" },
            { c: "🌾", n: "Sheaf Of Rice" },
            { c: "⚡", n: "Lightning" },
            { c: "💡", n: "Light Bulb" },
            { c: "🌪", n: "Wind Face" },
            { c: "🌊", n: "Water Wave" },
            { c: "🚲", n: "Bicycle" },
            { c: "🪴", n: "Potted Plant" },
            { c: "🪵", n: "Wood" },
            { c: "🪨", n: "Rock" }
        ]
    },
    {
        name: "Text Formatting",
        note: "Lucide: Text formatting (260) — typography U+2000+, general punctuation",
        symbols: [
            { c: "¶", n: "Pilcrow" },
            { c: "§", n: "Section Sign" },
            { c: "•", n: "Bullet" },
            { c: "†", n: "Dagger" },
            { c: "‡", n: "Double Dagger" },
            { c: "′", n: "Prime" },
            { c: "″", n: "Double Prime" },
            { c: "⁂", n: "Asterism" },
            { c: "※", n: "Reference Mark" },
            { c: "‰", n: "Per Mille" },
            { c: "‱", n: "Per Ten Thousand" },
            { c: "—", n: "Em Dash" },
            { c: "–", n: "En Dash" },
            { c: "…", n: "Ellipsis" },
            { c: "«", n: "Left Guillemet" },
            { c: "»", n: "Right Guillemet" },
            { c: "‹", n: "Single Left Guillemet" },
            { c: "›", n: "Single Right Guillemet" },
            { c: "“", n: "Left Double Quote" },
            { c: "”", n: "Right Double Quote" },
            { c: "‘", n: "Left Single Quote" },
            { c: "’", n: "Right Single Quote" },
            { c: "‚", n: "Single Low Quote" },
            { c: "„", n: "Double Low Quote" },
            { c: "©", n: "Copyright" },
            { c: "®", n: "Registered" },
            { c: "™", n: "Trademark" },
            { c: "℗", n: "Sound Recording Copyright" },
            { c: "№", n: "Numero" },
            { c: "º", n: "Ordinal Indicator" },
            { c: "ª", n: "Feminine Ordinal" },
            { c: "°", n: "Degree" },
            { c: "¦", n: "Broken Bar" },
            { c: "¤", n: "Currency Sign" },
            { c: "→", n: "Rightward Arrow" },
            { c: "⇒", n: "Rightward Double Arrow" },
            { c: "←", n: "Leftward Arrow" },
            { c: "⇐", n: "Leftward Double Arrow" },
            { c: "‐", n: "Hyphen" },
            { c: "‑", n: "Non Breaking Hyphen" },
            { c: "‒", n: "Figure Dash" },
            { c: "‟", n: "Double Low Reversed Quote" },
            { c: "‛", n: "Single Reversed Quote" },
            { c: " ", n: "Em Space" },
            { c: " ", n: "En Space" },
            { c: " ", n: "Thin Space" },
            { c: "​", n: "Zero Width Space" },
            { c: "‌", n: "Zero Width Non Joiner" },
            { c: "‍", n: "Zero Width Joiner" },
            { c: "﻿", n: "Byte Order Mark" },
            { c: "⁠", n: "Word Joiner" },
            { c: "·", n: "Middle Dot" },
            { c: "․", n: "One Dot Leader" },
            { c: "‥", n: "Two Dot Leader" }
        ]
    },
    {
        name: "Time & Calendar",
        note: "Lucide: Time & calendar (62) — clocks U+1F550+",
        symbols: [
            { c: "⌛", n: "Hourglass Done" },
            { c: "⏳", n: "Hourglass Flowing" },
            { c: "⏰", n: "Alarm Clock" },
            { c: "⏱", n: "Stopwatch" },
            { c: "⏲", n: "Timer Clock" },
            { c: "⌚", n: "Watch" },
            { c: "🕐", n: "One O Clock" },
            { c: "🕑", n: "Two O Clock" },
            { c: "🕒", n: "Three O Clock" },
            { c: "🕓", n: "Four O Clock" },
            { c: "🕔", n: "Five O Clock" },
            { c: "🕕", n: "Six O Clock" },
            { c: "🕖", n: "Seven O Clock" },
            { c: "🕗", n: "Eight O Clock" },
            { c: "🕘", n: "Nine O Clock" },
            { c: "🕙", n: "Ten O Clock" },
            { c: "🕚", n: "Eleven O Clock" },
            { c: "🕛", n: "Twelve O Clock" },
            { c: "🕜", n: "One Thirty" },
            { c: "🕝", n: "Two Thirty" },
            { c: "🕞", n: "Three Thirty" },
            { c: "🕟", n: "Four Thirty" },
            { c: "🕠", n: "Five Thirty" },
            { c: "🕡", n: "Six Thirty" },
            { c: "🕢", n: "Seven Thirty" },
            { c: "🕣", n: "Eight Thirty" },
            { c: "🕤", n: "Nine Thirty" },
            { c: "🕥", n: "Ten Thirty" },
            { c: "🕦", n: "Eleven Thirty" },
            { c: "🕧", n: "Twelve Thirty" },
            { c: "📅", n: "Calendar" },
            { c: "📆", n: "Tear Off Calendar" },
            { c: "🗓", n: "Spiral Calendar" },
            { c: "🔔", n: "Bell" }
        ]
    },
    {
        name: "Tools",
        note: "Lucide: Tools (73)",
        symbols: [
            { c: "✂", n: "Black Scissors" },
            { c: "✎", n: "Lower Right Pencil" },
            { c: "✏", n: "Pencil" },
            { c: "✐", n: "Upper Right Pencil" },
            { c: "✒", n: "Black Nib" },
            { c: "✍", n: "Writing Hand" },
            { c: "⚒", n: "Hammer And Pick" },
            { c: "⚗", n: "Alembic" },
            { c: "⚖", n: "Scales" },
            { c: "⛓", n: "Chains" },
            { c: "⚙", n: "Gear" },
            { c: "🔧", n: "Wrench" },
            { c: "🔨", n: "Hammer" },
            { c: "🛠", n: "Hammer And Wrench" },
            { c: "🪛", n: "Axe" },
            { c: "🪚", n: "Carpentry Saw" },
            { c: "🧰", n: "Toolbox" },
            { c: "🔩", n: "Nut And Bolt" },
            { c: "⛒", n: "Trident" },
            { c: "🗜", n: "Clamp" },
            { c: "🧭", n: "Compass" },
            { c: "⚠", n: "Warning Sign" }
        ]
    },
    {
        name: "Transportation",
        note: "Lucide: Transportation (64)",
        symbols: [
            { c: "✈", n: "Airplane" },
            { c: "🚗", n: "Car" },
            { c: "🚕", n: "Taxi" },
            { c: "🚙", n: "Sport Utility Vehicle" },
            { c: "🚌", n: "Bus" },
            { c: "🚎", n: "Trolleybus" },
            { c: "🚓", n: "Fire Engine" },
            { c: "🚑", n: "Ambulance" },
            { c: "🚒", n: "Police Car" },
            { c: "🚐", n: "Bus Front" },
            { c: "🚚", n: "Delivery Truck" },
            { c: "🚛", n: "Articulated Lorry" },
            { c: "🚜", n: "Tractor" },
            { c: "🏎", n: "Racing Car" },
            { c: "🏍", n: "Motorcycle" },
            { c: "🛵", n: "Motor Scooter" },
            { c: "🚲", n: "Bicycle" },
            { c: "🛴", n: "Kick Scooter" },
            { c: "🛹", n: "Skateboard" },
            { c: "🚦", n: "Vertical Traffic Light" },
            { c: "⛽", n: "Fuel Pump" },
            { c: "🚧", n: "Construction Sign" },
            { c: "🚥", n: "Horizontal Traffic Light" },
            { c: "⚓", n: "Anchor" },
            { c: "⛵", n: "Sailboat" },
            { c: "🚢", n: "Ship" },
            { c: "🛩", n: "Small Airplane" },
            { c: "🛫", n: "Airplane Departure" },
            { c: "🛬", n: "Airplane Arrival" },
            { c: "🚁", n: "Helicopter" },
            { c: "🚟", n: "Suspension Railway" },
            { c: "🚠", n: "Mountain Cableway" },
            { c: "🚅", n: "High Speed Train" }
        ]
    },
    {
        name: "Travel",
        note: "Lucide: Travel (71)",
        symbols: [
            { c: "✈", n: "Airplane" },
            { c: "🧳", n: "Luggage" },
            { c: "🛃", n: "Customs" },
            { c: "🛂", n: "Passport Control" },
            { c: "🛄", n: "Baggage Claim" },
            { c: "🛅", n: "Left Luggage" },
            { c: "🛏", n: "Bed" },
            { c: "🛌", n: "Sleeping Accommodation" },
            { c: "🛎", n: "Bellhop Bell" },
            { c: "🚺", n: "Restroom" },
            { c: "🚉", n: "Station" },
            { c: "🗺", n: "World Map" },
            { c: "🧭", n: "Compass" },
            { c: "🗽", n: "Statue Of Liberty" },
            { c: "🗼", n: "Tokyo Tower" },
            { c: "🏯", n: "Japanese Castle" },
            { c: "🏰", n: "Castle" },
            { c: "⛪", n: "Church" },
            { c: "🕌", n: "Mosque" },
            { c: "🕍", n: "Synagogue" },
            { c: "⛩", n: "Shinto Shrine" },
            { c: "⛰", n: "Mountain" },
            { c: "⛱", n: "Beach With Umbrella" },
            { c: "⛺", n: "Tent" },
            { c: "🏔", n: "Snow Capped Mountain" },
            { c: "🏕", n: "Campsite" },
            { c: "🏖", n: "Beach" },
            { c: "🏜", n: "Desert" },
            { c: "🏞", n: "National Park" },
            { c: "🏘", n: "Stadium" },
            { c: "🏟", n: "Stadium" }
        ]
    },
    {
        name: "Weather",
        note: "Lucide: Weather (51) — misc symbols U+2600–26FF",
        symbols: [
            { c: "☀", n: "Sun" },
            { c: "☁", n: "Cloud" },
            { c: "☂", n: "Umbrella" },
            { c: "☃", n: "Snowman" },
            { c: "☄", n: "Comet" },
            { c: "★", n: "Black Star" },
            { c: "☆", n: "White Star" },
            { c: "☇", n: "Lightning" },
            { c: "☈", n: "Thunderstorm" },
            { c: "☉", n: "Sun Pointing" },
            { c: "☊", n: "Ascending Node" },
            { c: "☋", n: "Descending Node" },
            { c: "☌", n: "Conjunction" },
            { c: "☍", n: "Opposition" },
            { c: "☎", n: "Telephone" },
            { c: "☏", n: "White Telephone" },
            { c: "☔", n: "Umbrella With Rain" },
            { c: "☕", n: "Hot Beverage" },
            { c: "☘", n: "Shamrock" },
            { c: "⛄", n: "Snowman Without Snow" },
            { c: "⛅", n: "Sun Behind Cloud" },
            { c: "⛈", n: "Thunder Cloud And Rain" },
            { c: "⛆", n: "Ophiuchus" },
            { c: "⛇", n: "Very Heavy Snow" },
            { c: "🌤", n: "Sun Behind Small Cloud" },
            { c: "🌥", n: "Sun Behind Large Cloud" },
            { c: "🌦", n: "Sun Behind Rain Cloud" },
            { c: "🌧", n: "Cloud With Rain" },
            { c: "🌨", n: "Cloud With Snow" },
            { c: "🌩", n: "Cloud With Lightning" },
            { c: "🌪", n: "Cloud With Tornado" },
            { c: "🌫", n: "Fog" },
            { c: "🌬", n: "Wind Blowing Face" },
            { c: "🌀", n: "Cyclone" },
            { c: "🌈", n: "Rainbow" },
            { c: "🌙", n: "Crescent Moon" },
            { c: "⚡", n: "High Voltage" },
            { c: "❄", n: "Snowflake" },
            { c: "💧", n: "Droplet" },
            { c: "⌚", n: "Watch" }
        ]
    }
];

if (typeof window !== "undefined") {
    window.CATEGORIES = CATEGORIES;
}
if (typeof module !== "undefined" && module.exports) {
    module.exports = CATEGORIES;
}
